@ -1,6 +1,6 @@
FROM fusuf/whatsasena:latest

RUN git clone https://github.com/dumi123wabot/KING-D-C/root/WhatsAsenaDuplicated
RUN git clone https://github.com/dumi123wabot/KING-D-C /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
